### ISSUE TITLE
Colorpicker input field visible on semi transparent colors

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-colorpicker#11]
@blackbaud-conorwright commented on [Wed Nov 21 2018](https://github.com/blackbaud/skyux2/issues/2183)

### Expected behavior
I should not be able to see the colorpicker's input text field inside the button.

### Actual behavior
When I make the color transparent (and the color isn't white), I can see the text inside the button.

### Steps to reproduce
1. Go to the colorpicker demo: https://developer.blackbaud.com/skyux/components/colorpicker
2. Input this hex color: #002dff
3. Set the transparency range to about half
4. Submit the color
5. See the text inside the colored button

### Plunker
You can just use the demo:
https://developer.blackbaud.com/skyux/components/colorpicker

### Severity
Low

### Impact
Low

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.1`
