### ISSUE TITLE
Many color picker types are not exported from `@skyux/colorpicker`

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-colorpicker#13]
### Expected behavior
You should be able to access many of the types used by `SkyColorpickerOutput` and `SkyColorpickerResult` such as `SkyColorpickerRgba`.

### Actual behavior
These types are not exported through the main module and must be imported through a more explicit path.

### Severity
Low

### Impact
Slight annoyance knowing where to import.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
