### ISSUE TITLE
Multiple instances of color picker shouldn't be open at once

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-colorpicker#14]
In cases where a form has multiple color pickers, the user can end up in a state with multiple pickers open at once. 

UX will need to determine the best approach to avoiding this.

![image (3)](https://user-images.githubusercontent.com/13765813/58713041-cb8ba780-838f-11e9-8e20-0b6e63281dee.png)

**Comment by Blackbaud-SteveBrush** [comment]
This change may need some design guidelines.
