### ISSUE TITLE
Colorpicker modal has inconsistent vertical height and shows vertical scrollbar

### ISSUE THREAD

**Issue by jeffbdye** [blackbaud/skyux-colorpicker#26]
### Expected behavior
The colorpicker modal should always be the same height and not scrollable.

### Actual behavior
The colorpicker modal has a height that is too small and causes overflow in the y axis.

### Steps to reproduce
Open the current colorpicker demo, open any colorpicker modal. Notice that the height differs based on the height of the containing window/browser.
https://developer.blackbaud.com/skyux/components/colorpicker

### Severity
Cosmetic

### Impact
All colorpickers

**Comment by Blackbaud-RobertDixon** [comment]
Note that for Safari this issue can be particularly confusing, as scrollbars are not normally shown.  So in this example, the colorpicker's confirmation buttons are not showing, and there's no visual indicator to the user that the buttons even exist:

![image](https://user-images.githubusercontent.com/25301661/69459371-9c069800-0d3f-11ea-89e1-75d487d57212.png)

**Comment by Blackbaud-SteveBrush** [comment]
This is probably related to the latest version of `@skyux/popovers` and how it handles max-height (same issue with datepicker's calendar).

**Comment by Blackbaud-AlexKingman** [comment]
It definitely is. I just looked into it and we're forcing all dropdowns to respect the new 1/2 viewport height rule. I think we need to evaluate the best way for colorpicker to ignore this.

**Comment by Blackbaud-AlexKingman** [comment]
A possible workaround in the meantime is for consumers to override the `max-height` style:
```
.sky-popover-max-height .sky-popover {
    max-height: initial;
}
```
