### ISSUE TITLE
Colorpicker shows background color of the page or parentElement when the selected color is transparent.

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-colorpicker#50]
### Expected behavior
 - Something else (probably a checkered background) to indicate that the selected color is transparent in the preview outside of the dropdown.

### Actual behavior
 - Just shows the color of the parentElement or body as if it was the selected color

### Steps to reproduce
 1. Load a color picker with allowTransparency set to true.
 2. Set the color's transparency to 0/fully transparent
 3. Apply and see the preview color showing the background

### Severity
Cosmetic

### Impact
Low - I don't think transparency is often allowed in our pages and If it is I don't think customers use it extensively

**Comment by blackbaud-conorwright** [comment]
Note: I consider this **blocking my migration to Skyux 4**, because a recent change to the color picker was to hide the ng-content which I had been using to insert my checkered background for this case. On the plus side though, that prompted me to question why I didn't just contribute it in the first place, so now everyone can have it :D

**Comment by Blackbaud-SteveBrush** [comment]
Duplicate: https://github.com/blackbaud/skyux-colorpicker/issues/42

**Comment by blackbaud-conorwright** [comment]
@Blackbaud-SteveBrush I don't think that is a duplicate. I'm only changing the view of the preview outside of the popover and only for transparent. I think what Scott is asking for is like a black border or something around the in popover preview to show that the color is white since the square blends in to be invisible otherwise
