### ISSUE TITLE
Can't access Apply/Close buttons when popup when the color picker is in a sweet spot for AOT builds

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-colorpicker#57]
### Expected behavior
The color picker should reposition itself to always be fully visible

### Actual behavior
![image](https://user-images.githubusercontent.com/14927732/88434322-f2940c80-cdcd-11ea-80c5-d272edc5c5b2.png)

### Steps to reproduce
This seems to only happen for AOT builds where the color picker is in the wrong place at the wrong time. If you have access to a environment that can access our Email SPA, that's the easiest way to reproduce it.

It is also reported that this is a Chrome specific bug that doesn't happen in IE or Firefox.

### Severity
Client found but marked as High in Azure DevOps.

[AB#1544240](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1544240)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.0.4`
